import { StyleSheet } from "react-native";
import { COLORS } from "../../styles/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.WHITE,
  },
  main: {
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "center",
    backgroundColor: COLORS.GRAY_600,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    paddingBottom: 40,
  },
  text: {
    fontSize: 14,
    lineHeight: 14 * 1.3,
    fontFamily: "Roboto_400Regular",
    color: COLORS.GRAY_300,
    textAlign: "center",
  },
  inputs: {
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 16,
    marginBottom: 24,
    gap: 16,
  },
  input: {
    height: 48,
    width: "100%",
    maxWidth: "70%",
    backgroundColor: COLORS.WHITE,
    borderRadius: 8,
    paddingHorizontal: 16,
    fontSize: 16,
    lineHeight: 16 * 1.3,
    fontFamily: "Roboto_400Regular",
  },
  login: {
    height: 48,
    width: "100%",
    maxWidth: "70%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.PURPLE,
    borderRadius: 8,
    marginBottom: 16,
  },
  loginText: {
    textAlign: "center",
    fontSize: 16,
    lineHeight: 16 * 1.3,
    fontFamily: "Roboto_700Bold",
    letterSpacing: 0.2,
    color: COLORS.WHITE,
  },
  footer: {
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    paddingTop: 56,
    paddingBottom: 80,
  },
  googleBtnBorder: {
    height: 48,
    width: "100%",
    maxWidth: "70%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.WHITE,
    borderColor: COLORS.GRAY_200,
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  googleBtn: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  googleText: {
    flex: 1,
    textAlign: "center",
    fontSize: 16,
    lineHeight: 16 * 1.3,
    fontFamily: "Roboto_700Bold",
    letterSpacing: 0.2,
    color: COLORS.GRAY_100,
  },
  createAccountBtn: {
    height: 48,
    width: "100%",
    maxWidth: "70%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.GRAY_600,
    borderRadius: 8,
  },
  createAccountText: {
    textAlign: "center",
    fontSize: 16,
    lineHeight: 16 * 1.3,
    fontFamily: "Roboto_700Bold",
    letterSpacing: 0.2,
    color: COLORS.GRAY_100,
  },
});
